// SDR output validators — Fase D of ADR-009.
//
// Post-checks on text generated by the LLM (redactarMensajeSDR). Templates
// from the composer skip these validators on purpose: they're already vetted
// deterministic strings. The LLM, on the other hand, drifts — it forgets to
// end with a question, it promises "casos de éxito" that don't exist, it
// apologizes for prior turns that never happened.
//
// Each validator is a pure function with an explicit autofix. The pipe emits
// 'sdr_validator_fired' to LangFuse on activation so dashboards can spot
// drift (e.g. endsWithQuestion firing > 10% of LLM turns means the directive
// in SP-SDR-03 is rotten and needs a prompt fix, not a validator-bandaid).
//
// Anti-pattern guard: validators must NEVER decide flow. They only correct
// or annotate text. Flow decisions live in the FSM / reducer.

import type { ConvContext } from './context.js'
import { langfuse } from '../../integrations/langfuse.js'

// ─── Validator contract ──────────────────────────────────────────────────────

export interface ValidatorOutcome {
  fixed: string
  triggered: boolean
  autofixType?: string
}

export interface Validator {
  name: string
  apply(text: string, ctx: ConvContext): ValidatorOutcome
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

const SENTENCE_SPLIT = /(?<=[.!?…])\s+/

function splitSentences(text: string): string[] {
  return text.split(SENTENCE_SPLIT).map(s => s.trim()).filter(Boolean)
}

function lastSentence(text: string): string {
  const sentences = splitSentences(text)
  return sentences[sentences.length - 1] ?? text.trim()
}

// CTA pool — picked deterministically by turnCount so the same conversation
// doesn't repeat the same CTA twice in a row. Wording mirrors what real reps
// would say at this point in the funnel.
const CTA_POOL = [
  '¿Te hace sentido para tu finca?',
  '¿Cómo registran hoy las labores en tu operación?',
  '¿Te suena con lo que vivís?',
  '¿Querés que te muestre cómo se vería con tu cultivo?',
] as const

function pickCta(ctx: ConvContext): string {
  return CTA_POOL[ctx.turnCount % CTA_POOL.length]!
}

// ─── Validator: endsWithQuestion ─────────────────────────────────────────────
// The most common SDR bug: LLM closes the pitch with a flat declarative
// ("...te ahorrás horas y evitás pérdidas.") and the prospect goes silent
// because there's nothing to reply to. Autofix appends a CTA from the pool.

export const endsWithQuestion: Validator = {
  name: 'endsWithQuestion',
  apply(text, ctx) {
    const trimmed = text.trim()
    if (!trimmed) return { fixed: trimmed, triggered: false }

    const last = lastSentence(trimmed)
    // Both forms of question marks: '?' and the trailing of '¿...?'. Some
    // models drop the opening '¿' but keep the closing one — both pass.
    if (/[?]\s*$/.test(last)) return { fixed: trimmed, triggered: false }

    const cta = pickCta(ctx)
    return {
      fixed: `${trimmed} ${cta}`,
      triggered: true,
      autofixType: 'append_cta',
    }
  },
}

// ─── Validator: noFalsePromises ──────────────────────────────────────────────
// Wasagro does NOT have case studies / "casos de éxito" / customer testimonials
// to share. The LLM has invented them in prior conversations ("te paso un PDF
// con casos de éxito"), which destroys trust the moment the prospect asks for
// the PDF and we can't deliver. Validator removes the offending sentence and
// emits telemetry so a recurring drift triggers a prompt fix.

const FALSE_PROMISE_PATTERN = /\b(casos? de [ée]xito|case stud(?:y|ies)|pdf con casos|nuestros clientes (?:han|tienen) logrado|testimonios? de (?:otros )?clientes)\b/i

export const noFalsePromises: Validator = {
  name: 'noFalsePromises',
  apply(text, _ctx) {
    const sentences = splitSentences(text)
    const kept = sentences.filter(s => !FALSE_PROMISE_PATTERN.test(s))
    if (kept.length === sentences.length) {
      return { fixed: text, triggered: false }
    }
    // Re-join with single space — splitSentences strips the original
    // whitespace anyway, so we don't lose information.
    return {
      fixed: kept.join(' ').trim(),
      triggered: true,
      autofixType: 'drop_sentence',
    }
  },
}

// ─── Validator: noUnnecessaryApology ─────────────────────────────────────────
// The LLM keeps adding "Disculpá si te confundí antes..." or "Perdón por la
// pregunta anterior..." even when the prior turn was a clean discovery
// question. It surprises prospects ("why are you apologizing?") and signals
// uncertainty. Strip any leading apology phrase when there's no prior bot
// error to apologize for.

const APOLOGY_PATTERN = /^\s*(disculp[áa]\s+(?:la\s+)?(?:pregunta|si\s+te\s+confund[íi])[^.!?]*[.!?]\s*|perdón\s+(?:por\s+)?[^.!?]*[.!?]\s*)/i

export const noUnnecessaryApology: Validator = {
  name: 'noUnnecessaryApology',
  apply(text, ctx) {
    // Only fire when the previous bot turn was NOT an error — we have no
    // first-class "errored last turn" flag, so use lastBotAction as proxy:
    // if the bot was asking a question or pitching, there's nothing to
    // apologize for. The 'none' bucket includes fresh sessions where the
    // LLM has zero reason to apologize.
    const APOLOGY_OK_AFTER: ReadonlyArray<ConvContext['lastBotAction']> = []
    if (APOLOGY_OK_AFTER.includes(ctx.lastBotAction)) {
      return { fixed: text, triggered: false }
    }
    if (!APOLOGY_PATTERN.test(text)) {
      return { fixed: text, triggered: false }
    }
    const cleaned = text.replace(APOLOGY_PATTERN, '').trim()
    return {
      fixed: cleaned,
      triggered: true,
      autofixType: 'strip_leading_apology',
    }
  },
}

// ─── Pipeline ────────────────────────────────────────────────────────────────

export const VALIDATORS: ReadonlyArray<Validator> = [
  noUnnecessaryApology,
  noFalsePromises,
  endsWithQuestion,
]

export interface PipeResult {
  text: string
  triggered: Array<{ name: string; autofixType?: string }>
}

// Pure pipe — chains validators left-to-right. Each validator sees the output
// of the previous one. The pipe itself doesn't touch LangFuse so it can be
// unit-tested without mocking. The caller (validateMessage) handles telemetry.
export function pipeValidators(text: string, ctx: ConvContext, validators: ReadonlyArray<Validator> = VALIDATORS): PipeResult {
  let current = text
  const triggered: PipeResult['triggered'] = []
  for (const v of validators) {
    const out = v.apply(current, ctx)
    if (out.triggered) {
      const entry: PipeResult['triggered'][number] = { name: v.name }
      if (out.autofixType !== undefined) entry.autofixType = out.autofixType
      triggered.push(entry)
      current = out.fixed
    }
  }
  return { text: current, triggered }
}

// Wrapper that emits the LangFuse event. Use from router.ts.
export function validateMessage(text: string, ctx: ConvContext, traceId: string): string {
  const result = pipeValidators(text, ctx)
  if (result.triggered.length > 0) {
    langfuse.trace({ id: traceId }).event({
      name:  'sdr_validator_fired',
      level: 'DEFAULT',
      input: {
        validators: result.triggered,
        before:     text.slice(0, 300),
        after:      result.text.slice(0, 300),
        fsmState:   ctx.fsmState,
        lastBotAction: ctx.lastBotAction,
      },
    })
  }
  return result.text
}
